name: Check update everyday

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check update
        env:
          token: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          publish_date1=$(curl -sX GET "https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest" | awk '/published_at/{print $4;exit}' FS='[""]')
          build_date=$(curl -sX GET "https://hub.docker.com/v2/repositories/zyao89/adguardhome-with-smartdns/" | grep -oP '(?<="last_updated": ")[^"]*' | cut -d '.' -f1 | awk '{print $1"Z"}')
          if [ $publish_date1 \> $build_date ]
            then
              curl -X POST https://hub.docker.com/api/build/v1/source/fee33443-84ac-4f61-b7d4-03fa8bf73b22/trigger/$token/call/
            else
              echo up to date
          fi
